







const menu = {
    list() {
        return [
            {
                "backMenu":[
                    {
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"管理员管理",
                                "menuJump":"列表",
                                "tableName":"users"
                            }
                        ],
                        "menu":"管理员管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"用户管理",
                                "menuJump":"列表",
                                "tableName":"yonghu"
                            }
                        ],
                        "menu":"用户管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "报表",
                                    "删除"
                                ],
                                "menu":"失物招领管理",
                                "menuJump":"列表",
                                "tableName":"shiwuzhaoling"
                            },
                            {
                                "buttons":[
                                    "查看",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"失物招领留言管理",
                                "menuJump":"列表",
                                "tableName":"shiwuzhaolingLiuyan"
                            }
                        ],
                        "menu":"失物招领管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "删除"
                                ],
                                "menu":"失物认领管理",
                                "menuJump":"列表",
                                "tableName":"shiwurenling"
                            }
                        ],
                        "menu":"失物认领管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"宣传视频管理",
                                "menuJump":"列表",
                                "tableName":"xuanchuanshipin"
                            }
                        ],
                        "menu":"宣传视频管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"物品挂失管理",
                                "menuJump":"列表",
                                "tableName":"wupinguashi"
                            },
                            {
                                "buttons":[
                                    "查看",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"物品挂失留言管理",
                                "menuJump":"列表",
                                "tableName":"wupinguashiLiuyan"
                            }
                        ],
                        "menu":"物品挂失管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "删除"
                                ],
                                "menu":"论坛管理",
                                "menuJump":"列表",
                                "tableName":"forum"
                            }
                        ],
                        "menu":"论坛管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"公告管理",
                                "menuJump":"列表",
                                "tableName":"news"
                            }
                        ],
                        "menu":"公告管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"轮播图管理",
                                "menuJump":"列表",
                                "tableName":"config"
                            }
                        ],
                        "menu":"轮播图信息"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"公告类型管理",
                                "menuJump":"列表",
                                "tableName":"dictionaryNews"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"物品类型管理",
                                "menuJump":"列表",
                                "tableName":"dictionaryShiwuzhaoling"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "删除",
                                    "修改"
                                ],
                                "menu":"宣传视频类型管理",
                                "menuJump":"列表",
                                "tableName":"dictionaryXuanchuanshipin"
                            }
                        ],
                        "menu":"基础数据管理"
                    }
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"管理员",
                "tableName":"users"
            },
            {
                "backMenu":[
                    {
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "认领",
                                    "删除"
                                ],
                                "menu":"失物招领管理",
                                "menuJump":"列表",
                                "tableName":"shiwuzhaoling"
                            },
                            {
                                "buttons":[
                                    "查看",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"失物招领留言管理",
                                "menuJump":"列表",
                                "tableName":"shiwuzhaolingLiuyan"
                            }
                        ],
                        "menu":"失物招领管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "审核"
                                ],
                                "menu":"失物认领管理",
                                "menuJump":"列表",
                                "tableName":"shiwurenling"
                            }
                        ],
                        "menu":"失物认领管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"宣传视频管理",
                                "menuJump":"列表",
                                "tableName":"xuanchuanshipin"
                            }
                        ],
                        "menu":"宣传视频管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"物品挂失管理",
                                "menuJump":"列表",
                                "tableName":"wupinguashi"
                            },
                            {
                                "buttons":[
                                    "查看",
                                    "修改",
                                    "删除"
                                ],
                                "menu":"物品挂失留言管理",
                                "menuJump":"列表",
                                "tableName":"wupinguashiLiuyan"
                            }
                        ],
                        "menu":"物品挂失管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"公告管理",
                                "menuJump":"列表",
                                "tableName":"news"
                            }
                        ],
                        "menu":"公告管理"
                    }
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"用户",
                "tableName":"yonghu"
            }
        ]
    }
}
export default menu;
